### ISSUE TITLE
Fix grammar/spelling typos

### ISSUE THREAD

**Issue by cesargom** [yellowme/youst-kotlin#12]
- Typos on the welcome text
    - **programing -> programming**. Actually, either one is fine, but if we're using American English, perhaps it should be changed to **programming** for consistency.
- Typos on the challenge descriptions
    - In Crazy Lists: **looks -> look**
    - In Listen to Me: **result on -> result in**
    - In All about the details: **new on a team -> Change it to 'a new team member'.**

**Comment by luisburgos** [comment]
Could you list all the changes we need to make? @cesargom
