### ISSUE TITLE
Create a kotlin code style importable xml

### ISSUE THREAD

**Issue by javikin** [yellowme/youst-kotlin#20]
Create an xml file for Kotlin code style for android development. On this way, everyone can importer on his local configuration.. [https://github.com/grandcentrix/AndroidCodeStyle/](Example)

**Comment by luisburgos** [comment]
Consider using a [git pre push hook](https://proandroiddev.com/ooga-chaka-git-hooks-to-enforce-code-quality-11ce8d0d23cb) to run [klint checks](https://ktlint.github.io/)

**Comment by luisburgos** [comment]
We should also consider the IDE default auto-formatting and evaluate to create our own. @marioguillermo
