### ISSUE TITLE
Add info and collaboration files

### ISSUE THREAD

**Issue by luisburgos** [yellowme/youst-kotlin#3]
## Acceptance Criteria

- Add README file
- Add CONTRIBUTING file
- Add LICENSE file

## Considerations

- Consider using reference to https://help.github.com/en/articles/closing-issues-using-keywords

## Topics

- Branch naming
- Branch deletion after merge
- Who is responsible for merges?

**Comment by LuisBurgos** [comment]
Add reference to https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by luisburgos** [comment]
Closed by #26
